version: 3

tasks:
  default:
    cmds:
      - task list -a
    silent: true
  run:
    cmds:
      - go run ./cmd/
  build:
    desc: Build the Go binary locally
    cmds:
      - go build -o dist/dash ./cmd/
